-- Initial schema for DataLab Studio.
-- PostgreSQL stores dataset metadata only; raw files live on local disk.

CREATE TABLE dataset (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(512) NOT NULL,
    stored_path        VARCHAR(1024) NOT NULL,
    status             VARCHAR(32)  NOT NULL,
    row_count          BIGINT       NOT NULL DEFAULT 0,
    column_count       INTEGER      NOT NULL DEFAULT 0,
    file_size_bytes    BIGINT       NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_dataset_created_at ON dataset (created_at DESC);

CREATE TABLE dataset_column (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id  BIGINT       NOT NULL REFERENCES dataset (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    position    INTEGER      NOT NULL,
    column_type VARCHAR(32)  NOT NULL,
    is_nullable BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_dataset_column_position UNIQUE (dataset_id, position)
);

CREATE INDEX idx_dataset_column_dataset_id ON dataset_column (dataset_id);
